export const ROUTES = {
    HOME: "/",
    REGISTRATION: "/registration",
    GENDER: "/gender-predictor",
    AGE: "/age-predictor",
    COUNTER: "/counter",
    ABOUT: "/about-us",
    CONTACTS: "/contacts",
    ACCOUNT: "/account",
    ACCSETTINGS: "/account/settings",
    ACCINFO: "/account/info",
    PRODUCT: "/products",
    PRODUCTID: "/products/:id",
    USERLIST: "/users",
    USERPAGE: "/users/:id",
};